logging:
  level:
    org:
      hibernate: DEBUG
      springframework:
        data:
          jpa: DEBUG

spring:
  jpa:
    hibernate:
      ddl-auto: update

---
spring:
  config:
    activate:
      on-profile: rds
  datasource:
    username: ${rds_username}
    password: ${rds_password}
    url: jdbc:mysql://${rds_endpoint}/${rds_database}

---
spring:
  config:
    activate:
      on-profile: rds-ssl
  datasource:
    username: ${rds_username}
    password: ${rds_password}
    url: jdbc:mysql://${rds_endpoint}/${rds_database}?useSSL=true&requireSSL=true&verifyServerCertificate=true&enabledSslProtocolSuites=TLSv1.2,TLSv1.1,TLSv1,SSLv3